Event updates
CraftTweaker/CraftTweaker pull request #1145
Opened 2021-01-23 07:03 UTC by Darkhax

This PR exposes several new events.

- LivingDeathEvent
- LivingHurtEvent
- LivingHealEvent
- XPChange
- LevelChange
- AdvancementEvent
- DestroyItemEvent
- FishItemEvent

Also exposed DamageSource's getters.

2021-01-23 07:29 UTC, jaredlll08 requested changes

2021-01-23 07:29 UTC, jaredlll08 commented on src/main/java/com/blamejared/crafttweaker/impl_native/event/entity/player/ExpandPlayerDestroyItemEvent.java
> +        return internal.getOriginal();
IItemStacks are a bit of a special case in terms of natives, can you change this to return an IItemStack instead (just wrap `internal.getOriginal()` in a `new MCItemStack(internal.getOriginal()`

This also solves the mutability issue as `MCItemStack` is immutable.

2021-01-23 07:29 UTC, jaredlll08 commented on src/main/java/com/blamejared/crafttweaker/impl_native/event/entity/player/xp/ExpandLevelChangedEvent.java
> + * is positive the levels are being added. If they are negative levels are
> If they are negative levels are

shouldn't this be:
```
If they are negative, levels are
```

First read through of this I was confused as to what `negative levels` was.

2021-01-23 07:29 UTC, jaredlll08 commented on src/main/java/com/blamejared/crafttweaker/impl_native/event/entity/player/xp/ExpandXpChangedEvent.java
> + * positive the xp is being added. If the xp is negative the xp is being
> If the xp is negative the xp is being

shouldn't this be:
```
If the xp is negative, the xp is being
```
?

2021-01-24 02:31 UTC, Darkhax commented
@jaredlll08 I made the changes you asked for.

2021-01-24 02:35 UTC, merged