mutable item stacks
CraftTweaker/CraftTweaker pull request #1208
Opened 2021-03-22 05:12 UTC by friendlyhj

The PR adds 1.16 MutableItemStack to 1.12. I have checked and changed methods to ensure the origin IItemStack still immutable.

2021-03-22 17:22 UTC, democat3457 commented
doesn't contenttweaker have a mutableitemstack

2021-03-22 23:18 UTC, friendlyhj commented
Of course I know, but the CoT mutable itemstack only can be used in CoT scripts, not in CrT events.

2021-03-24 17:29 UTC, jaredlll08 requested changes

2021-03-24 17:29 UTC, jaredlll08 commented on CraftTweaker2-API/src/main/java/crafttweaker/api/util/IRandom.java
> +public interface IRandom {
please add a `nextFloat`

2021-03-24 17:29 UTC, jaredlll08 commented
I believe this looks good, but please can you test it with some big 1.12 modpacks to make sure the mutable changes don't cause any issues

2021-03-25 00:18 UTC, democat3457 commented on CraftTweaker2-API/src/main/java/crafttweaker/api/util/IRandom.java
> +public interface IRandom {
can you also add the methods that are found in MathHelper that take a rand as a parameter - for example, the nextX with min and max bound methods

2021-03-25 00:21 UTC, democat3457 commented on CraftTweaker2-API/src/main/java/crafttweaker/api/util/IRandom.java
> +public interface IRandom {
(these are the `getInt`, `getRandomUUID`, `nextFloat`, and `nextDouble` methods, specifically)

2021-03-25 00:53 UTC, friendlyhj commented
> I believe this looks good, but please can you test it with some big 1.12 modpacks to make sure the mutable changes don't cause any issues

I believe these changes don't

2021-03-25 13:49 UTC, merged