Patches
CraftTweaker/CraftTweaker pull request #1245
Opened 2021-04-23 14:46 UTC by friendlyhj

2021-04-23 14:55 UTC, jaredlll08 requested changes

2021-04-23 14:55 UTC, jaredlll08 commented on CraftTweaker2-MC1120-Main/src/main/java/crafttweaker/mc1120/item/MCItemStack.java
> +        CraftTweakerAPI.logWarning("Actually, the immutable ItemStack is not damageable. Use `mutable` method to make it mutable first!");
```suggestion
        CraftTweakerAPI.logWarning("Cannot damage IItemStack, make it mutable with `mutable` first!");
```

2021-04-23 15:08 UTC, merged

2021-04-24 04:46 UTC, democat3457 commented
@friendlyhj attemptDamageItem is still present in the iitemstack expand

2021-04-24 04:57 UTC, friendlyhj commented
> @friendlyhj attemptDamageItem is still present in the iitemstack expand

Damn, it is absolutely because I rebased 1.12 branch after the move method commit.

2021-04-24 05:06 UTC, democat3457 commented
I figured, since the file diff is weird and shows addition of random leftovers from a previous commit