getTag method returns MapData
CraftTweaker/CraftTweaker pull request #1316
Opened 2021-07-09 02:06 UTC by friendlyhj

2021-07-09 22:02 UTC, jaredlll08 requested changes
This is also a breaking change, if a mod was calling this method before, they would need to recompile against the new code since the method signature would have changed.

2021-07-09 22:02 UTC, jaredlll08 commented on src/main/java/com/blamejared/crafttweaker/api/item/IItemStack.java
> +        return new MapData(getInternal().getTag());
This doesn't take into account if the tag is null, which NBT converter did.

2021-07-10 07:50 UTC, kindlich commented on src/main/java/com/blamejared/crafttweaker/api/item/IItemStack.java
> +        return tag == null ? null : new MapData(tag);
Why not just create an overload in NBTConverter like
```java
public static MapData convert(CompoundNBT compound) {
    return compound == null ? null : new MapData(compound);
}

public static IData convert(INBT nbt) {
    if(nbt == null) {
        return null;
    }

    switch(nbt.getId()) {
       //...
        case 10:
            return convert((CompoundNBT)nbt);
        //...
    }
}

2021-07-10 07:50 UTC, kindlich commented on src/main/java/com/blamejared/crafttweaker/api/item/IItemStack.java
> +        return new MapData(getInternal().getTag());
If the suggestion of an overload is accepted, then you can just keep NBTConverter.convert here ^^

2021-08-02 04:20 UTC, friendlyhj commented
Close it. Since we can auto down cast now. The last thing the PR would add is to mark `@ZenCodeType.Nullable` on `MapData#getAt` and `MapData#put` method. It is too easy. I think you can directly make a commit about it.

2021-08-02 04:20 UTC, closed without merging