Add default ChancedOutputs IRecipeComponent
CraftTweaker/CraftTweaker pull request #1566
Opened 2022-10-14 20:14 UTC by Witixin1512

2022-10-14 20:20 UTC, jaredlll08 requested changes

2022-10-14 20:20 UTC, jaredlll08 commented on Common/src/main/java/com/blamejared/crafttweaker/api/recipe/component/BuiltinRecipeComponents.java
> +            CraftTweakerConstants.rl("output/chanced_outputs"),
Kinda weird to specify output twice
```suggestion
            CraftTweakerConstants.rl("output/chanced_items"),
```

2022-10-14 20:20 UTC, jaredlll08 commented on Common/src/main/java/com/blamejared/crafttweaker/api/recipe/component/RecipeComponentEqualityCheckers.java
> +
Could this not just be `Objects::equals`?

2022-10-14 21:11 UTC, jaredlll08 commented on Common/src/main/java/com/blamejared/crafttweaker/api/recipe/component/RecipeComponentEqualityCheckers.java
> +import java.util.List;
These imports are now useless

2022-10-14 21:11 UTC, jaredlll08 approved these changes

2022-10-14 21:17 UTC, Witixin1512 commented on Common/src/main/java/com/blamejared/crafttweaker/api/recipe/component/RecipeComponentEqualityCheckers.java
> +import java.util.List;
![image](https://user-images.githubusercontent.com/73248264/195945556-69a67d84-6a24-41c5-b886-f6a2763dbd9c.png)
I disagree

2022-10-15 20:41 UTC, merged

2022-10-15 21:15 UTC, TheSilkMiner commented
Why is this component a single component even if it is clearly saying it's composite by being `List<T>`?